### ISSUE TITLE
Apparent syntax errors in script

### ISSUE THREAD

**Issue by tripleee** [dogukankurnaz/virtualbox-fix#1]
> `$(kill -15 $(ps aux | grep "VBoxClient --draganddrop" | grep "Sl" | awk '{print $2;}')) | $(/usr/bin/VBoxClient --draganddrop) | $(/usr/bin/VBoxClient --clipboard)`

means:

* run `ps aux` and extract the PID of `VBoxClient`; you seem to be reinventing `pidof VBoxClient`, poorly
* run `kill -15` on the result, and pipe it to
* ... the _output_ of `/usr/bin/VBoxClient --draganddrop`
* ... and pipe that to the output of `/usr/bin/VBoxClient --clipboard`

Based on what [documentation I could find for VBoxClient,](http://www.linux-commands-examples.com/VBoxClient) it seems like you really mean

```
# Kill VBoxClient drag and drop service
pkill -f VBoxClient --draganddrop
# Restart drag and drop service
VBoxClient --draganddrop
# Restart clipboard service
VBoxClient --clipboard
```

The obnoxious nonessential output and `sleep 2` should at the very least be possible to disable.

**Comment by dogukankurnaz** [comment]
Thank you for your feedback. I will arrange it as you want.

Edit: The code works perfectly correctly. Today I struggled with the same problem and assigned the script I created to the .desktop shortcut and ran it. The problem is gone.

**Comment by tripleee** [comment]
Your script probably happens to do what you want, but it has several bugs. Probably run it through http://shellcheck.net/ if you don't trust my judgment. One of the symptoms is that it will display several error message on the console when you run it.

**Comment by dogukankurnaz** [comment]
i did mate. Thank you for sharing shell_analysis website =)
